[window]
opacity = 0.9

[font]
size = 14.0


# Данную настройку можно менять в зависимости от системы
# На windows у меня запускается wsl

#[terminal.shell]
#program = "wsl.exe"

# Тема flat_remix

[colors.primary]
background = '#272a34'
foreground = '#FFFFFF'

[colors.normal]
black   = '1F2229'
red     = '#EC0101'
green   = '#47D4B9'
yellow  = '#FF8A18'
blue    = '#277FFF'
magenta = '#D71655'
cyan    = '#05A1F7'
white   = '#FFFFFF'

[colors.bright]
black   = '#1F2229'
red     = '#D41919'
green   = '#5EBDAB'
yellow  = '#FEA44C'
blue    = '#367bf0'
magenta = '#BF2E5D'
cyan    = '#49AEE6'
white   = '#FFFFFF'
